ФЗ 9 спринта (1 ревью)
RuslanDergachev/java-filmorate pull request #3
Opened 2022-05-22 10:23 UTC by RuslanDergachev

2022-05-23 19:19 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
еще один вариант автовайринга бинов: 
если над классом повесить ломбок аннотацию @AllArgsConstructor, а поля, которые мы хотим заавтовайрить сделать final, то можно явно не прописывать конструктор с аннотацией @Autowired

2022-05-23 20:13 UTC, Fleaman777 requested changes

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +
лишняя пустая строка

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/NotFoundException.java
> +public class NotFoundException extends RuntimeException{
этот эксепшен и ValidationException можно было бы переместить в пекекедж exception, там им больше место подходит :)

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    List<Film> bestFilms;
поля можно сделать private

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                film.getLikes().add(userId);
хороший метод для того, что бы выполнить его в стриме, 
так же как и deleteLikeFilm

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
супер, отличная реализация этого метода

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private int compare(Film p0, Film p1) {
просто как еще один из вариантов сравневания фильмов, можно классом Film симплементить интерфейс Comparable, реализовать его метод compareTo(), тогда в стриме в методе sorted() не нужно будет отдельно вызывать метод compare

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    List<User> mutualFriends;
здесь тоже можно сделать поля private

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.getUserById(friendId).getFriends().add(userId);
getUserById(....).getFriends() - потенциальное место для NPE,  
хорошо было бы разорвать эту цепочку и проверить на null

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(userId) != null) {
отлично, здесь от NPE обезопасился :)

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return listFilms;
можно сразу вернуть new ArrayList<>(films.values()); без создания доп локальной переменной

2022-05-23 20:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void validationDataReleaseFilm(Film film) throws ValidationException {
по правильному, storage классы отвечают только за доставание объектов из мест хранения, 
за их валидацию должны отвечать отдельно созданные для этого сервисы

2022-05-24 09:19 UTC, RuslanDergachev commented
Замечания исправил.

2022-05-25 16:27 UTC, merged